fix: address generator in spec
Conflux-Chain/helios pull request #14
Opened 2021-04-09 03:32 UTC by yqrashawn

2021-04-09 06:44 UTC, angelia-yuqi-personal requested changes

2021-04-09 07:21 UTC, yqrashawn commented on packages/rpc-engine/index.js
> +import * as rpcerr from '@cfxjs/json-rpc-error'
I take it as a single word meaning "error constructors of all kind of rpc errors". 

If use `rpcErr` it should be callled `rpcErrs`.

So I think rpcerr is better.

2021-04-09 07:23 UTC, angelia-yuqi-personal commented on packages/rpc-engine/index.js
> +import * as rpcerr from '@cfxjs/json-rpc-error'
Do you mean you take a new single word `rpcerr`? But I worry it's not a reasonable word.

2021-04-09 09:14 UTC, zctocm commented on packages/rpc-engine/index.js
> +import * as rpcerr from '@cfxjs/json-rpc-error'
I think `rpcErr` is a better word to use.

1. We know we can handle the error of RPC by this file, but we do not know how many errors defined in this file
2. `jsonRpcErr`,`jsonRpcError`,`rpcErr`,`rpcError` which are the shorthand ways to express the name of file `json-rpc-error`

2021-04-12 03:01 UTC, angelia-yuqi-personal approved these changes

2021-04-12 03:01 UTC, merged