feat: fix some bugs
Conflux-Chain/helios pull request #294
Opened 2021-12-08 12:30 UTC by angelia-yuqi-personal

PORTAL-1615
PORTAL-1616
PORTAL-1644
PORTAL-1645

2021-12-08 12:30 UTC, angelia-yuqi-personal commented
Task linked: [PORTAL-1616 切换网络后，Address 发生改变，需要有一个 Toast 提示](https://app.clickup.com/t/3719212/PORTAL-1616)

2021-12-08 12:30 UTC, angelia-yuqi-personal commented
Task linked: [PORTAL-1645 Transaction Submit 成功页咱不用要了](https://app.clickup.com/t/3719212/PORTAL-1645)

2021-12-08 12:30 UTC, angelia-yuqi-personal commented
Task linked: [PORTAL-1644 Custom Nonce 我们给个建议的值吧，当前这笔交易的 Nonce](https://app.clickup.com/t/3719212/PORTAL-1644)

2021-12-08 12:30 UTC, angelia-yuqi-personal commented
Task linked: [PORTAL-1615 Send Transaction 没有输入值的时候不要提示错误](https://app.clickup.com/t/3719212/PORTAL-1615)

2021-12-10 03:55 UTC, yqrashawn requested changes

2021-12-10 03:55 UTC, yqrashawn commented on packages/estimate-tx/index.js
>      await Promise.all(promises)
remove this line

2021-12-10 03:57 UTC, angelia-yuqi-personal commented on packages/estimate-tx/index.js
>      await Promise.all(promises)
done

2021-12-10 08:56 UTC, yqrashawn submitted a review, later dismissed

2021-12-10 09:33 UTC, yqrashawn approved these changes

2021-12-10 09:41 UTC, merged