feat: set(not takeover) window.ethereum by default
Conflux-Chain/helios pull request #915
Opened 2022-04-21 10:25 UTC by yqrashawn

PORTAL-2918

2022-04-21 10:25 UTC, angelia-yuqi-personal commented
Task linked: [PORTAL-2918 当未安装 metamask，即使 fluent 托管按钮没打开，连接 metamask 也能调起 fluent，默认不托管 metamask](https://app.clickup.com/t/3719212/PORTAL-2918)

2022-04-22 02:56 UTC, angelia-yuqi-personal requested changes

2022-04-22 02:56 UTC, angelia-yuqi-personal commented on packages/inpage/setup-inpage-provider.test.js
> +    it('shouldn not setup the provider on window.ethereum when already defined', async function () {
typo

2022-04-22 03:34 UTC, yqrashawn commented
typeo fixed

2022-04-22 03:35 UTC, angelia-yuqi-personal approved these changes

2022-04-22 06:41 UTC, zctocm approved these changes
> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/helios/915)* status: all files reviewed, 1 unresolved discussion (waiting on @yqrashawn)



<!-- Sent from Reviewable.io -->

2022-04-22 07:08 UTC, merged